{"name": "test_get_endpoints_response_time[/blog/]", "status": "failed", "statusDetails": {"message": "Failed: Request to https://rangoljx.github.io/blog/ failed with exception: Response time for https://rangoljx.github.io/blog/ was too long: 11.670095443725586 seconds\nassert 11.670095443725586 < 10", "trace": "endpoint = '/blog/'\n\n    @pytest.mark.parametrize(\"endpoint\", [\n        \"/\",  # 首页\n        \"/about.html\",  # 关于页面\n        \"/blog/\"  # 博客页面\n    ])\n    def test_get_endpoints_response_time(endpoint):\n        \"\"\"\n        测试网站不同端点的GET请求响应时间。\n        参数:\n            - endpoint (str): 要测试的网站端点。\n        测试方法:\n            - 构造完整的URL。\n            - 发送GET请求。\n            - 检查响应时间是否小于设定的阈值。\n        \"\"\"\n        try:\n            response = send_request(\"GET\", endpoint)  # 使用封装的请求函数\n            rtime = response['response_time']\n    \n            # 设定响应时间阈值（例如：1秒）\n            MAX_RESPONSE_TIME = 10\n    \n            # 检查响应时间是否在阈值范围内\n>           assert rtime < MAX_RESPONSE_TIME, f\"Response time for {BASE_URL}{endpoint} was too long: {rtime} seconds\"\nE           AssertionError: Response time for https://rangoljx.github.io/blog/ was too long: 11.670095443725586 seconds\nE           assert 11.670095443725586 < 10\n\ntests\\test_api.py:61: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nendpoint = '/blog/'\n\n    @pytest.mark.parametrize(\"endpoint\", [\n        \"/\",  # 首页\n        \"/about.html\",  # 关于页面\n        \"/blog/\"  # 博客页面\n    ])\n    def test_get_endpoints_response_time(endpoint):\n        \"\"\"\n        测试网站不同端点的GET请求响应时间。\n        参数:\n            - endpoint (str): 要测试的网站端点。\n        测试方法:\n            - 构造完整的URL。\n            - 发送GET请求。\n            - 检查响应时间是否小于设定的阈值。\n        \"\"\"\n        try:\n            response = send_request(\"GET\", endpoint)  # 使用封装的请求函数\n            rtime = response['response_time']\n    \n            # 设定响应时间阈值（例如：1秒）\n            MAX_RESPONSE_TIME = 10\n    \n            # 检查响应时间是否在阈值范围内\n            assert rtime < MAX_RESPONSE_TIME, f\"Response time for {BASE_URL}{endpoint} was too long: {rtime} seconds\"\n        except Exception as e:\n            # 捕获并打印异常，以便调试\n>           pytest.fail(f\"Request to {BASE_URL}{endpoint} failed with exception: {e}\")\nE           Failed: Request to https://rangoljx.github.io/blog/ failed with exception: Response time for https://rangoljx.github.io/blog/ was too long: 11.670095443725586 seconds\nE           assert 11.670095443725586 < 10\n\ntests\\test_api.py:64: Failed"}, "description": "\n    测试网站不同端点的GET请求响应时间。\n    参数:\n        - endpoint (str): 要测试的网站端点。\n    测试方法:\n        - 构造完整的URL。\n        - 发送GET请求。\n        - 检查响应时间是否小于设定的阈值。\n    ", "parameters": [{"name": "endpoint", "value": "'/blog/'"}], "start": 1733995000087, "stop": 1733995011757, "uuid": "a4180093-220d-44ac-9367-84587697c3eb", "historyId": "21de8563bcda27ef40eb20097381cbef", "testCaseId": "665eff6bdfbd75f244e4101b5dd24a7f", "fullName": "tests.test_api#test_get_endpoints_response_time", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_api"}, {"name": "host", "value": "LAPTOP-CP2FN3BV"}, {"name": "thread", "value": "33192-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_api"}]}